### ISSUE TITLE
maybe some bug

### ISSUE THREAD

**Issue by grassroadsZ** [FACINGS/eospyo#8]
hello, thanks your lib ,it work well on mac os, but when i work on centos ,it is worng

```shell
(.venv) [root@quant gamefi]# python3.8 -m venv .venv

(.venv) [root@quant gamefi]# python -V
Python 3.8.0a1
(.venv) [root@quant gamefi]# pwd
/home/Code/gamefi
(.venv) [root@quant gamefi]# ls
farmerworld.py
(.venv) [root@quant gamefi]# python farmerworld.py 
Traceback (most recent call last):
  File "farmerworld.py", line 5, in <module>
    import eospyo
  File "/home/Code/gamefi/.venv/lib/python3.8/site-packages/eospyo/__init__.py", line 1, in <module>
    from . import exc, types
  File "<fstring>", line 1
    (response=)
             ^
SyntaxError: invalid syntax
```
i used python venv ,did it not work on venv?

**Comment by edinhodiluviano** [comment]
Hello @grassroadsZ 
Thanks for the feedback,
It seems that the alpha version of python 3.8 you're using has no support to [f-strings equals](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging) (example bellow).
But the standard python 3.8 should have. Should work if you upgrade it. Let me know if it doesn't ; )

```
Python 3.8.0a1 (default, Feb 22 2019, 00:35:00) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 1
>>> f"{x=}"
  File "<fstring>", line 1
    (x=)
      ^
SyntaxError: invalid syntax
```

```
Python 3.8.0 (default, Nov 23 2019, 05:36:56) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 1
>>> f"{x=}"
'x=1'
>>> 
```
